// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotherInstitute.Models;

#nullable disable

namespace MotherInstitute.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420094714_AddTagline")]
    partial class AddTagline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotherInstitute.Models.AcademicSession", b =>
                {
                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.HasKey("NAME");

                    b.ToTable("ACADEMICSESSION", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.BedDetails", b =>
                {
                    b.Property<string>("BEDNO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BUILDING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLOOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BEDNO");

                    b.ToTable("BEDDETAILS", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Course", b =>
                {
                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.HasKey("NAME");

                    b.ToTable("COURSE", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Fees", b =>
                {
                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.HasKey("NAME");

                    b.ToTable("FEES", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Organization", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOGO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAILID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("REGDDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("REGDNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAGLINE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("ORGANIZATION", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentFees", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<decimal?>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FEESNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("STUDENTFEE", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentInstallment", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<decimal?>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("INSTALLMENTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("STUDENTINSTALLMENT", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentRegd", b =>
                {
                    b.Property<string>("STUDENTID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AADHARNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BEDNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLOODGROUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOARDNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CASTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLLEGENAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLLEGEROLLNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COURSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURRYR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOR")
                        .HasColumnType("datetime2");

                    b.Property<string>("FNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOB1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOB2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SESSION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STUDENTID");

                    b.ToTable("STUDENTREGD", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentSubjects", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("STUDENTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBJECT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("STUDENTSUB", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Subjects", b =>
                {
                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.HasKey("NAME");

                    b.ToTable("SUBJECTS", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.User", b =>
                {
                    b.Property<string>("LOGINID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("REGDDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LOGINID");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Visitors", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("STUDENTVISITORS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
