// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotherInstitute.Models;

#nullable disable

namespace MotherInstitute.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516115317_AddAddressColumn")]
    partial class AddAddressColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotherInstitute.Models.AcademicSession", b =>
                {
                    b.Property<string>("NAME")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.HasKey("NAME");

                    b.ToTable("ACADEMICSESSION", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.BedDetails", b =>
                {
                    b.Property<string>("BEDNO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BUILDING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLOOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BEDNO");

                    b.ToTable("BEDDETAILS", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Course", b =>
                {
                    b.Property<string>("NAME")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.HasKey("NAME");

                    b.ToTable("COURSE", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.EizocMember", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("EIZOCMEMBER", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Fees", b =>
                {
                    b.Property<string>("NAME")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.HasKey("NAME");

                    b.ToTable("FEES", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.MarketingAgent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MarketingAgents");
                });

            modelBuilder.Entity("MotherInstitute.Models.MarketingStudent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SchoolId");

                    b.ToTable("MarketingStudents");
                });

            modelBuilder.Entity("MotherInstitute.Models.Organization", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOGO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAILID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("REGDDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("REGDNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("ORGANIZATION", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.SchoolMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SchoolMasters");
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentExpense", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CATEGORY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PARTICULARS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SLNO");

                    b.HasIndex("STUDENTID");

                    b.ToTable("STUDENTEXPENSES", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentFees", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<decimal?>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FEESNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("STUDENTFEE", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentInstallment", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<decimal?>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("INSTALLMENTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("STUDENTINSTALLMENT", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentPayment", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SLNO");

                    b.HasIndex("STUDENTID");

                    b.ToTable("STUDENTPAYMENT", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentRegd", b =>
                {
                    b.Property<string>("STUDENTID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AADHARNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BEDNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLOODGROUP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BOARDNAME")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CASTE")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("COLLEGENAME")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("COLLEGEROLLNO")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("COURSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURRYR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOR")
                        .HasColumnType("datetime2");

                    b.Property<string>("FNAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GENDER")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IMAGE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MNAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MOB1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOB2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SESSION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STUDENTID");

                    b.ToTable("STUDENTREGD", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentSubjects", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("STUDENTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBJECT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("STUDENTSUB", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Subjects", b =>
                {
                    b.Property<string>("NAME")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.HasKey("NAME");

                    b.ToTable("SUBJECTS", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.User", b =>
                {
                    b.Property<string>("LOGINID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("REGDDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LOGINID");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.Visitors", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.ToTable("STUDENTVISITORS", (string)null);
                });

            modelBuilder.Entity("MotherInstitute.Models.MarketingStudent", b =>
                {
                    b.HasOne("MotherInstitute.Models.SchoolMaster", "SchoolMaster")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolMaster");
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentExpense", b =>
                {
                    b.HasOne("MotherInstitute.Models.StudentRegd", "Student")
                        .WithMany()
                        .HasForeignKey("STUDENTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MotherInstitute.Models.StudentPayment", b =>
                {
                    b.HasOne("MotherInstitute.Models.StudentRegd", "Student")
                        .WithMany()
                        .HasForeignKey("STUDENTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
